### Manipulando Matrizes

In [2]:
import numpy as np

In [3]:
arr1 = np.array([[1, 2, 3] , [4, 5, 6]])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
print(arr1.shape)

(2, 3)


In [6]:
#criando matriz 2x3, apenas com numero 1
arr2 = np.ones((2, 3))

In [7]:
print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
lista = [[5, 15, 20], [4, 16, 20], [1, 2, 3]]

In [9]:
#função matrix() para criar uma matriz a partir de uma lista de listas
arr3 = np.matrix(lista)

In [10]:
type(arr3)

numpy.matrix

In [11]:
print(arr3)

[[ 5 15 20]
 [ 4 16 20]
 [ 1  2  3]]


In [12]:
np.shape(arr3)

(3, 3)

In [13]:
arr3.size

9

In [14]:
print(arr3.dtype)

int32


In [15]:
arr3[2, 1]

2

In [16]:
arr3[0:2, 2]

matrix([[20],
        [20]])

In [17]:
arr3[1,]

matrix([[ 4, 16, 20]])

In [18]:
#alterando elemento da matriz
arr3[1, 0] = 100

In [19]:
print(arr3)

[[  5  15  20]
 [100  16  20]
 [  1   2   3]]


In [21]:
#forçando o tipo de dado particular
x = np.array([[1,2]])
y = np.array([1.0, 2.0])
z = np.array([1,2], dtype = np.float64)

In [22]:
print(x.dtype, y.dtype, z.dtype)

int32 float64 float64


In [23]:
arr4 = np.array([[24, 76, 58], [100, 200, 300], [2, 4, 6]], dtype = float)

In [24]:
print(arr4)

[[ 24.  76.  58.]
 [100. 200. 300.]
 [  2.   4.   6.]]


In [25]:
#Atributo itemsize para retornar o tamanho em bytes de cada elemento do array
arr4.itemsize

8

In [26]:
arr4.nbytes

72

In [28]:
arr4.ndim

2

### Manipulando Objetos de 3 e 4 Dimensões

In [29]:
arr_3d = np.array([
    [
        [1, 2, 3, 4],
        [5, 6, 7, 8],
        [9, 10, 11, 12]
    ],
    [
        [100, 200, 300, 400],
        [500, 600, 700, 800],
        [900, 1000, 2000, 3000]
    ]
])

In [30]:
print(arr_3d)

[[[   1    2    3    4]
  [   5    6    7    8]
  [   9   10   11   12]]

 [[ 100  200  300  400]
  [ 500  600  700  800]
  [ 900 1000 2000 3000]]]


In [31]:
arr_3d.ndim

3

In [33]:
arr_3d.shape #2 elementos, 3 linhas, 4 colunas

(2, 3, 4)

In [35]:
arr_3d[0, 2, 1]

10

In [36]:
#Array de 4 dimensões
arr_4d = np.array([
    [
        [
            [1, 2, 3, 4, 5],
            [6, 7, 8, 9, 10],
            [11, 12, 13, 14, 15],
            [16, 17, 18, 19, 20]
        ],
        [
            [21, 22, 23, 24, 25],
            [26, 27, 28, 29, 30],
            [31, 32, 33, 34, 35],
            [36, 37, 38, 39, 40]
        ],
        [
            [41, 42, 43, 44, 45],
            [46, 47, 48, 49, 50],
            [51, 52, 53, 54, 55],
            [56, 57, 58, 59, 60]
        ]
    ],
    [
        [
            [61, 62, 63, 64, 65],
            [66, 67, 68, 69, 70],
            [71, 72, 73, 74, 75],
            [76, 77, 78, 79, 80]
        ],
        [
            [81, 82, 83, 84, 85],
            [86, 87, 88, 89, 90],
            [91, 92, 93, 94, 95],
            [96, 97, 98, 99, 100]
        ],
        [
            [101, 102, 103, 104, 105],
            [106, 107, 108, 109, 110],
            [111, 112, 113, 114, 115],
            [116, 117, 118, 119, 120]
        ]
    ]
])

In [39]:
print(arr_4d) # 4 [] = estrutura 4D

[[[[  1   2   3   4   5]
   [  6   7   8   9  10]
   [ 11  12  13  14  15]
   [ 16  17  18  19  20]]

  [[ 21  22  23  24  25]
   [ 26  27  28  29  30]
   [ 31  32  33  34  35]
   [ 36  37  38  39  40]]

  [[ 41  42  43  44  45]
   [ 46  47  48  49  50]
   [ 51  52  53  54  55]
   [ 56  57  58  59  60]]]


 [[[ 61  62  63  64  65]
   [ 66  67  68  69  70]
   [ 71  72  73  74  75]
   [ 76  77  78  79  80]]

  [[ 81  82  83  84  85]
   [ 86  87  88  89  90]
   [ 91  92  93  94  95]
   [ 96  97  98  99 100]]

  [[101 102 103 104 105]
   [106 107 108 109 110]
   [111 112 113 114 115]
   [116 117 118 119 120]]]]


In [40]:
arr_4d.ndim

4

In [41]:
arr_4d.shape #2 grupos, 3 subgrupos, 4 linhas, 5 colunas

(2, 3, 4, 5)

In [43]:
arr_4d[0, 2, 1]

array([46, 47, 48, 49, 50])

In [44]:
arr_4d[0, 2, 1, 4]

50