### Maninpulação de Matrizes com NumPy

In [1]:
import numpy as np

In [4]:
np.__version__

'1.26.4'

#### Criando Arrays

In [5]:
#A partir de uma lista
arrl = np.array([10, 21, 32, 45, 50, 68, 100])

In [6]:
print(arrl)

[ 10  21  32  45  50  68 100]


In [7]:
type(arrl)

numpy.ndarray

Um array NumPy é uma estrutura de dados multidimensional. O NumPy fornece um objeto de matriz N-dimensional (ou ndarray) que é uma grade homogênea de elementos, geralmente números, que podem ser indexados por um conjunto de inteiros
São mais eficientes para armazenar e manipular grandes quantidades de dados, pois são implementados em Linguagem C e fornecem várias otimizações de desempenho. Além disso, o NumPy permite fácil leitura e escrita de arquivo de dados, integração com outras bibliotecas Python e suporte a operações em paralelo

In [9]:
arrl[5]

68

In [11]:
arrl[1:4] #Na indexação o segundo valor é exclusivo, ou seja não faz parte do resultado

array([21, 32, 45])

In [12]:
arrl[1:4+1]

array([21, 32, 45, 50])

In [13]:
indices = [1, 2, 5, 6]

In [14]:
arrl[indices]

array([ 21,  32,  68, 100])

In [15]:
#Máscara booleana para os elementos pares
mask = (arrl % 2 == 0)

In [16]:
mask

array([ True, False,  True, False,  True,  True,  True])

In [17]:
arrl[mask]

array([ 10,  32,  50,  68, 100])

In [18]:
# Alterando um elemento do array
arrl[2] = 25

In [19]:
print(arrl)

[ 10  21  25  45  50  68 100]


In [21]:
# não é possível incluir elemento de outro tipo
try:
    arrl[0] = 'novo elemento'
except:
    print('operação nao permitida')

operação nao permitida


#### Funções NumPy

In [22]:
arr2 = np.array([1, 2, 3, 4, 5, 6])

In [23]:
print(arr2)

[1 2 3 4 5 6]


In [26]:
arr2.cumsum() #soma acumulada

array([ 1,  3,  6, 10, 15, 21])

In [27]:
arr2.cumprod() #produto acumulado

array([  1,   2,   6,  24, 120, 720])

In [28]:
arr3 = np.arange(0, 50, 5) #cria um array NumPy contendo uma progressão aritmética a partir de um intervalo - start, stop, step

In [29]:
print(arr3)

[ 0  5 10 15 20 25 30 35 40 45]


In [30]:
type(arr3)

numpy.ndarray

In [31]:
np.shape(arr3) #formato

(10,)

In [33]:
print(arr3.dtype)

int32


In [34]:
arr4 = np.zeros(5)

In [35]:
print(arr4)

[0. 0. 0. 0. 0.]


In [36]:
#Retorna 1 nas posições em diagonal e 0 no restante = matriz diagonal
arr5 = np.eye(3)

In [37]:
print(arr5)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [39]:
arr6 = np.diag(np.array([1, 2, 3, 4]))

In [40]:
print(arr6)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [41]:
arr7 = np.array([True, False, False, True])

In [42]:
print(arr7)

[ True False False  True]


In [43]:
arr8 = np.array(['Linguagem Python', 'Linguagem R', 'SQL'])

In [44]:
print(arr8)

['Linguagem Python' 'Linguagem R' 'SQL']


In [45]:
print(np.linspace(0, 10)) #função linspace() é usada para criar uma sequencia de números igualmente espaçados dentro de um intervalo especificado

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [47]:
print(np.linspace(0, 10, 15))

[ 0.          0.71428571  1.42857143  2.14285714  2.85714286  3.57142857
  4.28571429  5.          5.71428571  6.42857143  7.14285714  7.85714286
  8.57142857  9.28571429 10.        ]


In [48]:
print(np.logspace(0, 5, 10)) #usada para criar uma sequencia de números igualmente espaçados em escala logarítmica dentro de um intervalo especificado

[1.00000000e+00 3.59381366e+00 1.29154967e+01 4.64158883e+01
 1.66810054e+02 5.99484250e+02 2.15443469e+03 7.74263683e+03
 2.78255940e+04 1.00000000e+05]
