### Slicing de Arrays Numpy

In [1]:
import numpy as np

In [5]:
arr1 = np.diag(np.arange(3)) 
#criado um array de 2 dimensões, porque a função diag() cria automaticamente uma matriz com uma diagonal, onde colocaremos 3 elementos

In [6]:
print(arr1)

[[0 0 0]
 [0 1 0]
 [0 0 2]]


In [7]:
arr1[1, 1]

1

In [8]:
arr1[1]

array([0, 1, 0])

In [10]:
arr1[:,2]

array([0, 0, 2])

In [11]:
arr2 = np.arange(10)
print(arr2)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
#start, end, step
arr2[2:9:3]

array([2, 5, 8])

In [13]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 22, 2, 4])

In [15]:
#Comparação item a item
a == b

array([False, False, False,  True])

In [16]:
#Comparação global
np.array_equal(a, b)

False

In [17]:
arr2.min()

0

In [18]:
arr2.max()

9

In [19]:
#Somando um valor a cada elemento do array
np.array([1, 2, 3]) + 1.5

array([2.5, 3.5, 4.5])

In [20]:
arr3 = np.array([1.2, 1.5, 1.6, 2.5, 3.5, 4.5])

In [21]:
#Arredondando os valores
arr4 = np.around(arr3)

In [22]:
print(arr4)

[1. 2. 2. 2. 4. 4.]


In [23]:
arr5 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

In [24]:
print(arr5)

[[1 2 3 4]
 [5 6 7 8]]


#### Método flatten() com NumPy é usado para criar uma cópia unidimensional de um array multidimensional. Isso significa que o método cria um novo array, que contém todos os elementos do array multidimensional original, mas que está organizado em uma única linha. A ordem dos elementos no novo array segue a ordem dos elementos no array multidimensional original

In [25]:
arr6 = arr5.flatten()

In [26]:
print(arr6)

[1 2 3 4 5 6 7 8]


In [27]:
arr7 = np.array([1, 2, 3])

In [28]:
print(arr7)

[1 2 3]


In [29]:
#Repetindo os elementos de um array
np.repeat(arr7, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [30]:
#Repetindo as combinações
np.tile(arr7, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [31]:
#Criando uma cópia
arr8 = np.copy(arr7)

In [32]:
print(arr8)

[1 2 3]
